image: python:3.10-slim

stages:
  - build
  - package

variables:
  BUILD_DIR: dist
  OUTPUT_NAME: dls-zmb-bot.exe
  ZIP_NAME: dls-zmb-bot.zip

before_script:
  - apt-get update && apt-get install -y --no-install-recommends wine wget unzip xvfb build-essential
  - pip install pyinstaller

build-exe:
  stage: build
  script:
    - pyinstaller --onefile --add-data "search.png:." --add-data "go.png:." --add-data "hands.png:." --add-data "camp.png:." --add-data "zmb.png:." --add-data "attack.png:." --add-data "force.png:." --add-data "forces.png:." --add-data "use_50.png:." --add-data "use_500.png:." --add-data "use_100.png:." --add-data "close.png:." --add-data "close2.png:." --add-data "close_adv.png:." --add-data "no_found.png:." --add-data "lvl_down.png:." --add-data "lvl_up.png:." --add-data "x.png:." main.py
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

package-zip:
  stage: package
  script:
    - cd $BUILD_DIR
    - cp ../*.png .
    - zip $ZIP_NAME $OUTPUT_NAME *.png
  artifacts:
    name: "dls-zmb-bot-$CI_COMMIT_SHORT_SHA"
    paths:
      - dist/$ZIP_NAME
    expire_in: 1 week
