name: Build EXE and Release

on:
  push:
    tags:
      - 'v*'  # например, v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build .exe with PyInstaller
        run: |
          pyinstaller --onefile `
            --add-data "search.png;." `
            --add-data "go.png;." `
            --add-data "hands.png;." `
            --add-data "camp.png;." `
            --add-data "zmb.png;." `
            --add-data "attack.png;." `
            --add-data "force.png;." `
            --add-data "forces.png;." `
            --add-data "use_50.png;." `
            --add-data "use_500.png;." `
            --add-data "use_100.png;." `
            --add-data "close.png;." `
            --add-data "close2.png;." `
            --add-data "close_adv.png;." `
            --add-data "no_found.png;." `
            --add-data "lvl_down.png;." `
            --add-data "lvl_up.png;." `
            --add-data "x.png;." main.py

      - name: Create ZIP archive
        run: |
          mkdir dist_zip
          copy dist\main.exe dist_zip\dls-zmb-bot.exe
          copy *.png dist_zip\
          powershell Compress-Archive -Path dist_zip\* -DestinationPath dls-zmb-bot.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: dls-zmb-bot.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
